name: everyday_sunday
description: Simple life. Better days. The best you.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # State Management  
  flutter_riverpod: ^2.4.0

  # UI
  lucide_icons: ^0.257.0

  # Navigation
  go_router: ^12.1.0

  # Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  # Networking
  dio: ^5.3.0

  # Functional Programming
  dartz: ^0.10.1

  # Utilities
  equatable: ^2.0.5
  intl: ^0.18.0

  # Features
  flutter_local_notifications: ^16.0.0
  pdf: ^3.10.0
  share_plus: ^7.2.0
  fl_chart: ^0.64.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.0

  # Testing
  mockito: ^5.4.0
  build_runner: ^2.4.0

  # Code Generation
  freezed: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
